### PR TITLE
Update readme

### LINKED ISSUE #67: Minify creates blank css file
For some reason when i minify my css files they become blank any ideas as to why.  Here is my Gulpfile.js
```
var gulp = require('gulp');
var watch = require('gulp-watch');
var liveReload  = require('gulp-livereload');
var concat   = require('gulp-concat');
var uglify   = require('gulp-uglify');
var rename   = require('gulp-rename');
var moment   = require('moment');
var notify   = require('gulp-notify');
var less = require('gulp-less');
var serve = require('gulp-serve');
var sass = require('gulp-sass');
var minifyCSS = require('gulp-minify-css');

require('gulp-help')(gulp, {
    description: 'Help listing.'
});

gulp.task('serve', 'A simple web server.', serve({
    root: ['client'],
    port: 3000
}));

gulp.task('uglify-js', 'Concat JavaScript into a single app.min.js.', function() {
    gulp.src(['js/ajax.js','js/custom.js','js/font-load.js'])
        .pipe(concat('app'))
        .on('error', notify.onError("Error: <%= error.message %>"))
        .pipe(uglify())
        .on('error', notify.onError("Error: <%= error.message %>"))
        .pipe(rename({
            extname: ".min.js"
        }))
        .pipe(gulp.dest('js'))
        .pipe(notify('Uglified JavaScript (' + moment().format('MMM Do h:mm:ss A') + ')'))
        .pipe(liveReload({
            auto: false
        }));
});

/*Comple less files into one css file */
gulp.task('web-less', 'Compile Styles', function() {
    gulp.src(['less/style.less','admin/ReduxCore/assets/css/admin.less'])
        .pipe(concat('style'))
        .pipe(less())
        .on('error', notify.onError("Error: <%= error.message %>"))
        .pipe(gulp.dest('css'))
        .pipe(minifyCSS({keepBreaks:true}))
        .pipe(notify('Compiled less (' + moment().format('MMM Do h:mm:ss A') + ')'))
        .pipe(liveReload({
            auto: false
        }));

});


/*Compile less files into one css file */
gulp.task('font-less', 'Compile Fonts', function() {
    gulp.src(['less/web-fonts.less'])
        .pipe(less())
        .on('error', notify.onError("Error: <%= error.message %>"))
        .pipe(minifyCSS({keepBreaks:true}))
        .pipe(gulp.dest('css'))
        .pipe(notify('Compiled less (' + moment().format('MMM Do h:mm:ss A') + ')'))
        .pipe(liveReload({
            auto: false
        }));

});


/*Minify css */
gulp.task('minify-css', function() {
    gulp.src('css/*.css')
        .pipe(minifyCSS({keepBreaks:false}))
        .pipe(gulp.dest('css/build/*.min'));
});


/*Watch for changes */
gulp.task('watch', 'Watch for changes and live reloads Chrome. Requires the Chrome extension \'LiveReload\'.', function() {
    liveReload.listen();

    watch('js/**/*.js', function() {
        gulp.start('uglify-js');
    });


    watch('less/**/*.less', function() {
        gulp.start('web-less');
    });

    watch('less/**/*.less', function() {
        gulp.start('font-less');
    });


    watch('css/**/*.css', function() {
        gulp.start('minify-css');

    });


});

gulp.task('default', ['watch', 'serve']);

```

### PR DESCRIPTION
**Pull request by shinnn**
* Use SVG badge instead of PNG badge
  * SVG badges look beautiful on retina displays.
* `Return` gulp.src streams in all examples. (close #67)

### CODE REVIEW

**Comment by shinnn** [comment]
@jonathanepollack

Could you add me as a maintainer? I'd happily maintain this repo and solve the issues [like this](https://github.com/jonathanepollack/gulp-minify-css/issues/67).

**Comment by jonathanepollack** [comment]
I was waiting forever for you to ask! You should now have collaborator status.

**Comment by shinnn** [comment]
@jonathanepollack 

Yay, thanks for inviting me to this awesome project! And, would you mind giving me owner access to the npm package? I can release a new version as soon as the issue is fixed.

**Comment by jonathanepollack** [comment]
On it right now!

**Comment by jonathanepollack** [comment]
Hmm... I can't seem to find a way to do this via npmjs.com . Can you drop me a link?

**Comment by jonathanepollack** [comment]
In theory `npm owner add shinnn` should do it, eh?

**Comment by shinnn** [comment]
Maybe this? https://docs.npmjs.com/cli/owner

```sh
$ npm owner add shinnn gulp-minify-css
$ npm owner ls
```

**Comment by jonathanepollack** [comment]
:+1:

Give it a shot now, and see if you can publish.

**Comment by shinnn** [comment]
Shown in the [npm package page](https://www.npmjs.com/package/gulp-minify-css). Thanks!

**Comment by shinnn** [comment]
Released v0.4.6 https://github.com/jonathanepollack/gulp-minify-css/commit/fe2d268f841e6c214c63f6d3e7fcb5407cb32bff

**Pull request merged**
