### PR TITLE
Add support for source maps

### PR DESCRIPTION
**Pull request by DominicBarnard**
Support for source maps with gulp-sourcemaps.

### CODE REVIEW

**Comment by adbl** [comment]
Fantastic! #34

**Comment by adbl** [comment]
My use case getting minification and `@import` inlining of regular css files after sass compilation (using `gulp-sass`), I haven't found any tool which can minify while preserving and referencing the original source map from sass yet.

Interesting results so far. Commenting out all `@import 'vanilla.css'` it seems to work great. The source map includes and refers to each original `.scss` file. Nice!

When I keep the vanilla css import, it is included in the source map and are referenced correctly, but another _empty_ `main.css` is added (sass compilation starts from `main.scss` and imports other partials), and all the source mappings now refer to this empty file. The original `.scss` files are still in the source map, but just not referenced anymore.

This may well be an issue with clean-css but I only use it through gulp, should I report it there? If you or @jonathanepollack have any input on this would be great.

**Comment by DominicBarnard** [comment]
That's interesting. I can't say i have ever done @import inlining of regular css files after sass compilation in my workflow so it's not something I've tested out before.
I'm about to call it a day but I'll try and take a look tomorrow.

**Comment by adbl** [comment]
As a work around I'm trying to do sass compilation and final minification in two steps, though it doesn't feel so gulpy. So I produce `css/main.css+map` from sass, then I added another file `css/index.css` which `@import`s both my other vanilla css and `main.css`.

But the results are strange, the sass source is references correctly from the map, the the sass source map contents are now empty... in the `.map` file I can see:
`["vanilla.css","../../../../../../source/bar/_foo.scss","../../../../../../source/main.scss"]`, I have no idea where all those `../` comes from.

**Comment by davidangel** [comment]
Looking forward to this being pulled in! Thanks @DominicBarnard !

**Comment by DominicBarnard** [comment]
So i'm still testing this on the back of @adbl issues at the mo.  There are def some issues around sources paths and importing files with existing sourcemaps.

**Comment by jonathanepollack** [comment]
Just let me know when you think this is ready for merge.

**Comment by DominicBarnard** [comment]
So @imported files with existing source maps are added to the sources list differently by clan-css so I've added a fix to handle that and it should work fine now.
The one caveat to this is that clean-css can't handle source maps with inlined source content yet so I've added a note to the readme to ensure the existing source maps can map properly back to the original source file.  
Unfortunately at the moment it appears some other plugins (autoprefixer and postcss in my tests) are exporting maps with incorrect sources paths. This is likely to trip up some workflows that modify files then output them to the disk so that minify can @import them.  I'll take a look at getting some fixes for those other plugins next.

@adbl as for your workflow, minify should be set to get it working now, bearing in mind the caveats I just mentioned.  However I think it would be really nice to have one of the css import plugins ([gulp-cssimport](https://github.com/unlight/gulp-cssimport), [gulp-import-css](https://github.com/yuguo/gulp-import-css)) fixed up to support gulp-sourcemaps - even inlining @imports from the gulp stream rather than having to dump to the disk first.

@jonathanepollack I think this should be set for you to merge now.  I'll keep an eye out for any related issues that come up.

**Comment by adbl** [comment]
Hmm, regarding existing source map with inlined content, I did see that working with sass -> gulp-minify-css. Or did you mean read from file?

Thanks a lot!

**Comment by DominicBarnard** [comment]
yes just from file.  If your using gulp-sourcemaps, gulp-minify-css doesn't pass any sourcemap into clean-css, it just lets clean-css produce a source map of it's own transformations, then we apply that to the gulp vinyl file source map which gets passed down stream in memory.  But when you @import a file with an existing sourcemap on disk, you rely on clean-css to read that as an input sourcemap. This is where clean-css won't support inlined content in the source map.  They do have an issue for it so maybe clean-css 3.1 or 3.2.

**Comment by DominicBarnard** [comment]
cool.  I've added to the list [Plugins-with-gulp-sourcemaps-support](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support)

**Pull request merged**
