### PR TITLE
Incomplete sources property in multi-step setup when using the base option in gulp.src

### LINKED ISSUE #64: Incomplete sources property in multi-step setup when using the base option in gulp.src
I discovered a really weird issue in my setup (which includes sass as a preprocessing step): When specifying the ```base``` option in ```gulp.src```, the ```sources``` property of the map returned is missing the included files.

## General setup

Gulpfile.js:
```js
gulp.src('css/main.scss', {
	base: '.'
})
.pipe(sourceMaps.init())
.pipe(sass())
.pipe(minifyCSS())
.pipe(write);
```

main.scss:
```sass
@import "_partial";

body {
	color: red;
}
```

## Result

- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/main.scss']```

## Fixes

**1. Omitting the ```base``` option:**
- Expected ```sources``` of map: ```['_partial.scss', 'main.scss']```
- Resulting ```sources``` of map: ```['_partial.scss', 'main.scss']```

This is not an option since I'm in fact passing an array to ```gulp.src```.

**2. Removing the minification step:**
- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```

Well, not really an option, too.

**3. Changing your plugin to pass the existing sourcemap [as a string](https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05#diff-168726dbe96b3ce427e7fedce31bb0bcL83):**
- Expected ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```
- Resulting ```sources``` of map: ```['css/_partial.scss', 'css/main.scss']```

I have added a test case to my fork: https://github.com/unic/gulp-minify-css/commit/4e6b5ec38a704c8eca5a45be490059e6f1b73a05

----------

Do you or @floridoo have any idea what's going on here?

### PR DESCRIPTION
**Pull request by backflip**
Fixes  #64

### CODE REVIEW

**Comment by jonathanepollack** [comment]
Can you fix these tests before we merge?

**Comment by backflip** [comment]
Apparently, node-sass (dependency of gulp-sass) does not work on 0.11 yet.
I see the following options:
* Removal of 0.11 from .travis.yml and running the tests on 0.10 instead
* Replacing gulp-sass with a different preprocessor
* Removing the preprocessor and directly adding its result to the repo instead (.css and .css.map files)

What would you prefer? It probably depends on how many people use gulp-minify-css in combination with gulp-sass. If I'm not the only one it could make sense to keep gulp-sass as a test dependency since breaking changes to the sourcemap behavior there would be detected here.

**Comment by shinnn** [comment]
> Replacing gulp-sass with a different preprocessor

+1

How about switching to [gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer)? It's more widely used than gulp-sass.

[gulp-sass](https://www.npmjs.com/package/gulp-sass):

> 113,920 downloads in the last month

[gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer):

> 126,930 downloads in the last month

**Comment by backflip** [comment]
Great idea. I will check whether I can reproduce the issue with gulp-autoprefixer.

**Comment by shinnn** [comment]
Ah, I overlooked the issue title. autoprefixer doesn't have something like `base` option...

**Comment by backflip** [comment]
The option is from ```gulp.src```.
However, I can't reproduce my issue with gulp-autoprefixer. There seems to be the need for a preprocessing step concatenating/combining files. I will check whether gulp-stylus or gulp-ruby-sass have the same issue as gulp-sass.

**Comment by shinnn** [comment]
> There seems to be the need for a preprocessing step concatenating/combining files.

If that is the real issue, maybe [gulp-concat](https://github.com/wearefractal/gulp-concat) meets our requirements. [It supports source map](https://github.com/wearefractal/gulp-concat#source-maps).

**Comment by jonathanepollack** [comment]
Just my two cents, if we're looking at the numbers.

There isn't a huge need to support v0.11.x, as it's most popular champion
(IMO) at the moment is Koa, and that only draws 16.5k/month downloads,
while express brought in more than a million.

That said, I actually use Koa, so I'd love to see v0.11 supported--I also
use `n`, and have no obligation to make my build env mirror my production
or dev environment, so I'm flexible.

**Comment by backflip** [comment]
* I can reproduce the issue using gulp-stylus (which works on 0.11)
* I can't reproduce it using gulp-concat

Apparently, there is a difference between the way gulp-sass and gulp-stylus handle sourcemaps and the way gulp-concat does.

I'd suggest using gulp-stylus for the test (and keep 0.11).

**Comment by shinnn** [comment]
> I'd suggest using gulp-stylus for the test (and keep 0.11).

:+1:

**Comment by backflip** [comment]
The last commit passed the Travis build.

@shinnn No worries, was a totally reasonable input.

**Comment by jonathanepollack** [comment]
Thanks for the hard work, guys! :+1:

**Comment by backflip** [comment]
Sorry for my slightly unstructured debugging. :)

**Comment by backflip** [comment]
Btw: I did not update the package.json so you might have to bump the version there.

**Comment by jonathanepollack** [comment]
Thats fine. I've taken care of everything, I believe.

**Comment by backflip** [comment]
Hm, the master's package.json is still on 0.4.4

**Comment by backflip** [comment]
I stand corrected, everything fine now. Possibly a caching issue.

**Comment by backflip** [comment]
Would it be possible to push this to npm?

**Comment by jonathanepollack** [comment]
Shit -- I'm sorry. I version'd it but forgot to publish.

Done.

**Pull request merged**
